### ISSUE TITLE
ModularityTests logs are too verbose

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/kickstart#100]
The `ModularyTests`, despite being disabled by default, produce a lot of log messages with the
`DEBUG` level of the following form:

```
...
10:16:56.964 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Processing class 'kickstart/welcome/WelcomeController'
...
```

In my opinion the level should be lowered to at least `INFO` to reduce noise in the build output.

Ideally, for the currently deployed repos, I would like to have an additional solution that avoids
pushing a commit to every repo (such as setting a global property via the `JAVA_TOOL_OPTIONS`
envvar in the runners).

**Comment by odrotbohm** [comment]
This should be fixed in the most recent version.
